apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: elearning
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - auth-service.yaml
  - course-catalog-service.yaml
  - gateway.yaml
  - frontend.yaml
