apiVersion: v1
kind: Secret
metadata:
  name: elearning-secrets
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "change-me"
  POSTGRES_DB: "elearning"
  JWT_SECRET: "change-me"
  AUTH_DATABASE_URL: "postgresql://postgres:change-me@postgres:5432/elearning?schema=auth"
  CATALOG_DATABASE_URL: "postgresql://postgres:change-me@postgres:5432/elearning?schema=catalog"
