apiVersion: v1
kind: Secret
metadata:
  name: elearning-secrets
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "1234"
  POSTGRES_DB: "elearning"
  JWT_SECRET: "l2gORoAeBwqD3gpTTzdyNtuAAzVCgi3saGeTnJlrhJhjuupwXuHeVVSowi9ZKcH2HK+C5yDdcPZ3jfQWr3BA4w=="
  AUTH_DATABASE_URL: "postgresql://postgres:1234@postgres:5432/elearning?schema=auth"
  CATALOG_DATABASE_URL: "postgresql://postgres:1234@postgres:5432/elearning?schema=catalog"
